# themes and music
define audio.Rest = "game/audio/Time for Rest.ogg"
define audio.moryTheme = "game/audio/mory_theme_v2.wav"
define audio.anitaThoughts = "game/audio/anitas_thoughts.wav"
define audio.eileanorScary = "game/audio/elleanor_is_scary.wav"
define audio.eileanorTheme = "game/audio/elleanors_theme.wav"
define audio.spook1 = "game/audio/general_spooky_track.wav"
define audio.vivianMetal = "game/audio/vivians_metal.wav"

# SFX for Act 1
define audio.angryCat1 = "game/audio/angrycat1.sfx.wav"
define audio.angryCat2 = "game/audio/angrycat2.sfx.wav"
define audio.barcodeScan = "game/audio/barcodescan.sfx.wav"
define audio.boxDropCoin = "game/audio/boxdropcoin.sfx.wav"
define audio.cafeGlassBreak = "game/audio/cafeglassbreak.sfx.wav"
define audio.catScratchDoor = "game/audio/catscratchdoor.sfx.wav"
define audio.clockTic = "game/audio/clocktick.sfx.wav"
define audio.creakingDoor = "game/audio/creakingdoor.sfx.wav"
define audio.doorClosing = "game/audio/doorclose.sfx.wav"
define audio.doorKnock1 = "game/audio/doorknock1.sfx.wav"
define audio.doorKnock2 = "game/audio/doorknock2.sfx.wav"
define audio.doorOpen = "game/audio/dooropen.sfx.wav"
define audio.doorPound = "game/audio/doorpound.sfx.wav"
define audio.elevatorDing = "game/audio/elevatording.sfx.wav"
define audio.footstepsWood = "game/audio/footstepswood.sfx.wav"
define audio.kettleWhistle = "game/audio/kettlewhistle.sfx.wav"
define audio.meow1 = "game/audio/meow1.sfx.wav"
define audio.meow2 = "game/audio/meow2.sfx.wav"
define audio.meow3 = "game/audio/meow3.sfx.wav"
define audio.meow4 = "game/audio/meow4.sfx.wav"
define audio.monsterGrowl = "game/audio/monstergrowl.sfx.wav"
define audio.movingBoxThump = "game/audio/movingboxthump.sfx.wav"
define audio.phoneRing = "game/audio/phonering.sfx.wav"