image void default = "void default.png" 
image void happy = "void happy.png" 
image void angry = "void angry.png"
image void startled = "void startled.png"
#chopped up image for different petting buttons
image void button = "void button.png"
image ear left = "left ear.png"
image ear right = "right ear.png"
image paws = "paws.png"
image tail = "tail.png"
